worker_processes 1;
events { 
    worker_connections 1024; 
}

http {
    server {
        listen 80;

        location /api/notebooks {
            proxy_pass http://notebooks;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/notes {
            proxy_pass http://notes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}