name: notees-backend

services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:80"
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USERNAME}:${NOTES_DB_PASSWORD}@notes-db/${NOTES_DB_NAME}
    develop:
      watch:
        - action: sync
          path: src
          target: /app/src
    networks:
      - notes-net
    depends_on:
      - notes-db
  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    networks:
      - notes-net
    volumes:
      - type: volume
        source: notes-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/init-mongo.js

volumes:
  notes-data:

networks:
  notes-net:
