FROM node:22-alpine AS development

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
CMD ["npm", "run", "dev"]

FROM node:22-alpine AS production-deps
WORKDIR /app
COPY package*.json .
RUN npm ci --omit=dev

FROM gcr.io/distroless/nodejs22 AS production
WORKDIR /app
COPY --from=production-deps /app/node_modules ./node_modules
COPY src src
CMD ["src/server.js"]